floridays_api:
    resource: "@ParamountHoaApiBundle/Resources/config/routing.yml"
    prefix:   /

floridays_entity:
    resource: "@ParamountHoaEntityBundle/Resources/config/routing.yml"
    prefix:   /

