floridays_api:
    resource: "@FloridaysApiBundle/Resources/config/routing.yml"
    prefix:   /

floridays_entity:
    resource: "@FloridaysEntityBundle/Resources/config/routing.yml"
    prefix:   /

